version: '3.8'

services:
  accounts-db:
    image: mongo:4.4
    container_name: accounts-db
    ports:
      - "27017:27017"
    volumes:
      - accounts-db-data:/data/db

  accounts-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://accounts-db:27017/accounts
    depends_on:
      - accounts-db

  transactions-db:
    image: mongo:4.4
    container_name: transactions-db
    ports:
      - "27018:27017"
    volumes:
      - transactions-db-data:/data/db

  transactions-service:
    build: ./transactions-service
    container_name: transactions-service
    ports:
      - "8001:8000"
    environment:
      MONGO_URI: mongodb://transactions-db:27017/transactions
      ACCOUNT_API_URL: http://accounts-service:8000
    depends_on:
      - transactions-db
      - accounts-service

volumes:
  accounts-db-data:
  transactions-db-data:
